theme: jekyll-theme-time-machine
title: Complete Ansible Training Guide
descripton: Materials for workshops and trainings for Ansible.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
